INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on /status [GET]
Traceback (most recent call last):
  File "C:\Users\Ayesha\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Ayesha\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Ayesha\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Ayesha\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Ayesha\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Ayesha\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Ayesha\nd064_course_1\exercises\python-helloworld\app.py", line 24, in status
    log('/status')
  File "C:\Users\Ayesha\nd064_course_1\exercises\python-helloworld\app.py", line 28, in log
    logging.debug(datetime.datetime.now() + ', ' + endpoint + 'endpoint was reached')
TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'str'
INFO:werkzeug:127.0.0.1 - - [22/Jun/2021 16:23:25] "GET /status HTTP/1.1" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
DEBUG:root:2021-06-22 16:24:40.734025, /statusendpoint was reached
INFO:werkzeug:127.0.0.1 - - [22/Jun/2021 16:24:40] "GET /status HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
DEBUG:root:2021-06-22 16:25:08.712765, /status endpoint was reached
INFO:werkzeug:127.0.0.1 - - [22/Jun/2021 16:25:08] "GET /status HTTP/1.1" 200 -
